"""150 predefined spending categories"""

PREDEFINED_CATEGORIES = [
    "Groceries",
    "Restaurants",
    "Coffee & Cafe",
    "Fast Food",
    "Alcohol & Bars",
    "Transportation",
    "Gas & Fuel",
    "Public Transit",
    "Ride Share",
    "Parking",
    "Car Maintenance",
    "Car Insurance",
    "Housing & Rent",
    "Mortgage",
    "Utilities",
    "Internet & Phone",
    "Home Maintenance",
    "Furniture & Decor",
    "Clothing",
    "Shoes",
    "Accessories",
    "Jewelry",
    "Personal Care",
    "Haircuts & Salon",
    "Gym & Fitness",
    "Healthcare",
    "Pharmacy",
    "Doctor Visits",
    "Dental Care",
    "Vision Care",
    "Entertainment",
    "Movies & Shows",
    "Concerts & Events",
    "Hobbies",
    "Books & Reading",
    "Subscriptions",
    "Streaming Services",
    "Music Services",
    "Travel",
    "Hotels & Accommodation",
    "Flights",
    "Vacation Activities",
    "Souvenirs",
    "Gifts",
    "Donations",
    "Charity",
    "Education",
    "Tuition",
    "Books & Supplies",
    "Insurance",
    "Life Insurance",
    "Health Insurance",
    "Taxes",
    "Bank Fees",
    "Pet Care",
    "Pet Food",
    "Veterinary",
    "Childcare",
    "Kids Activities",
    "Toys",
    "Electronics",
    "Software & Apps",
    "Office Supplies",
    "Sports Equipment",
    "Art Supplies",
    "Home Improvement",
    "Garden & Lawn",
    "Cleaning Supplies",
    "Laundry",
    "Dry Cleaning",
    "Beauty Products",
    "Skincare",
    "Makeup",
    "Massage & Spa",
    "Yoga & Meditation",
    "Therapy & Counseling",
    "Legal Fees",
    "Accounting",
    "Business Expenses",
    "Advertising",
    "Office Rent",
    "Coworking Space",
    "Professional Development",
    "Conferences & Events",
    "Networking",
    "Tools & Equipment",
    "Photography",
    "Video Production",
    "Music & Instruments",
    "Gaming",
    "Board Games",
    "Crafts & DIY",
    "Sewing & Knitting",
    "Home Decor",
    "Plants & Flowers",
    "Bike & Accessories",
    "Outdoor Gear",
    "Camping",
    "Hiking",
    "Skiing & Snowboarding",
    "Water Sports",
    "Team Sports",
    "Running",
    "Swimming",
    "Tennis & Racquet Sports",
    "Golf",
    "Martial Arts",
    "Dance Classes",
    "Cooking Classes",
    "Language Learning",
    "Online Courses",
    "Workshops",
    "Loans & Credit Cards",
    "Investment Fees",
    "Financial Planning",
    "Weddings",
    "Parties & Celebrations",
    "Flowers",
    "Bakery & Desserts",
    "Tobacco",
    "Lottery & Gambling",
    "ATM Fees",
    "Late Fees",
    "Postage & Shipping",
    "Storage",
    "Moving Expenses",
    "Furniture Rental",
    "Home Security",
    "Baby Care",
    "Baby Food",
    "Diapers",
    "Baby Gear",
    "School Supplies",
    "School Lunches",
    "Uniforms",
    "Newspapers & Magazines",
    "Comic Books",
    "Video Games",
    "Mobile Apps",
    "In-App Purchases",
    "Digital Downloads",
    "Cloud Storage",
    "Domain & Hosting",
    "VPN Services",
    "Crypto & Investments",
    "Stock Trading",
    "Emergency Fund",
    "Retirement Savings",
    "Savings",
    "Miscellaneous"
]
